seed: 10
batch_size: 16
total_batch_size: 16 
sample_q: 2304
num_pt: 7
inp_size: 48
queue_size: 320

train_dataset1:
  dataset:
    name: image-folder
    args:
      root_path: /your/path/to/train/HR/directory 
      cache: in_memory
  wrapper:
    name: sr-gaussian
    args:
      inp_size: 48
      sample_q: 2304
      augment: true

val_dataset1:
  dataset:
    name: image-folder
    args:
      root_path: /your/path/to/validation/HR/directory/
      cache: in_memory
  wrapper:
    name: sr-gaussian
    args:
      inp_size: 48
      sample_q: 2304

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

optimizer:
  name: adam
  args:
   lr: 1.e-4

multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_max: 1000
epoch_val: 1
epoch_save: 100

model:
  name: models
  args: {}
  SR:
    name: lte
    args:
      encoder_spec: 
        name: edsr_mod
        args:
          no_upsampling: true
      imnet_spec:
        name: mlp
        args:
          out_dim: 3
          hidden_list: [256, 256, 256]
  degrade:
    name: simsiam
    args:
      dim: 256 
  kernel:
    name: kernel
    args:
      {}
  path: /your/path/to/degradation/module/epoch-best.pth
    
wavelet:
  J: 1
  mode: zero
  wave: haar

blur:
  {}

  
  
